---
title: "Federal Employment Network"
author: "Blain Morin"
date: "4/7/2021"
runtime: shiny
output: 
    ioslides_presentation: 
      widescreen: yes
      transition: slower
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cahce = TRUE)

library(shiny)
library(readr)
library(tidyverse)
library(networkD3)
library(plotly)
library(readr)
library(statnet)
library(ndtv)
library(latticeExtra)

ref = read.csv("https://www.dropbox.com/s/xtt4emmz6txtbun/fed_agency_capacity_autonomy.csv?dl=1")
fed = read.csv("https://www.dropbox.com/s/18h5ppnj3srrxbx/r73_13_recoded_flows.csv?dl=1")


fed = fed %>%
    filter(AGYSUB_next != "EXIT") %>%
    filter(AGYSUB_next != "UKNOWN")

```


# Introduction

## Motivation

```{r}

test = fed %>%
  filter(AGYSUB_next != "EXIT")

test = test %>%
  filter(AGYSUB == "EP00" | AGYSUB_next == "EP00")

test2 = test %>%
  group_by(yr) %>%
  summarize(Sent = sum(AGYSUB == "EP00"), Received = sum(AGYSUB_next == "EP00"))

test2 = test2 %>%
  gather(key = Measure, value = Edge, 2:3)


p = test2 %>%
  ggplot(aes(x = yr, y = Edge)) +
  geom_line(aes(group = Measure, color = Measure), size = 1.5) +
  ylab("Number of Employees") +
  xlab("Year") +
  ggtitle("Environmental Protection Agency: Employees Sent and Received") +
  theme_bw() +
  scale_color_brewer(type = "qual", palette = 2) +
  scale_x_continuous(breaks = c(1973, seq(1976, 2010, by = 4,), 2012), minor_breaks = 1973:2012) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
ggplotly(p) %>%
    config(displayModeBar = FALSE)

```

# Data

## Network Visualization 

```{r}

fluidRow(
        column(3,
            numericInput("year",
                        "Year:",
                        min = 1974,
                        max = 2012,
                        value = 1974)),
        column(3,    
            sliderInput("nmin",
                         "Min Agency Size:",
                        min = 1, max = max(fed$n),
                        value = 10000)),
        column(2,    
               numericInput("send",
                           "Min. Sent:",
                           min = 1, max = 2000,
                           value = 10, step = 5)),
            
        column(2,    
            checkboxInput("EPA", "EPA", value = TRUE))
    )

```

```{r}

renderForceNetwork({
        # generate bins based on input$bins from ui.R
    
        if (input$EPA == TRUE){
            df = fed %>%
            filter(yr == input$year) %>%
            filter(n >= input$nmin) %>%
            filter(n_next >= input$send[1], n_next <= 2000) %>%
            filter(AGYSUB == "EP00" | AGYSUB_next == "EP00")
            
        } else {
            df = fed %>%
            filter(yr == input$year) %>%
            filter(n >= input$nmin) %>%
            filter(n_next >= input$send[1], n_next <= 2000)
        }
    
        
        sources = df %>%
            distinct(AGYSUB) %>%
            rename(label = AGYSUB)
        
        destinations = df %>%
            distinct(AGYSUB_next) %>%
            rename(label = AGYSUB_next)
        
        nodes = full_join(sources, destinations, by = "label") %>%
            rowid_to_column("id")
        
        edges = df %>%
            select(AGYSUB, AGYSUB_next, n_next) %>%
            rename(from = AGYSUB, to = AGYSUB_next, weight = n_next)
        
        nodes_d3 = mutate(nodes, id = id - 1) 
        
        nodevars = fed %>%
            group_by(AGYSUB) %>%
            slice(1) %>%
            select(AGYSUB, n, NAME)
        
        nodes_d3 = nodes_d3 %>%
            left_join(nodevars, by = c("label" = "AGYSUB")) 
        
        nodes_d3$n = nodes_d3$n %>% replace_na(500)
        
        nodes_d3[nodes_d3$label == "EXIT", "NAME"] = "EXIT" 
        
        nodes_d3$NAME = nodes_d3$NAME %>% replace_na("UNKNOWN")
        
        nodes_d3 = nodes_d3 %>%
            mutate(logn = sqrt(n))
        
        edges = left_join(edges, nodes, by = c("from" = "label")) %>%
            rename(fromid = id) %>%
            left_join(nodes, by = c("to" = "label")) %>%
            rename(toid = id) %>%
            select(fromid, toid, weight) %>%
            mutate(weight10 = sqrt(weight))
        
        edges_d3 = mutate(edges, fromid = fromid - 1, toid = toid - 1) 
        
        
        forceNetwork(Links = edges_d3, Nodes = nodes_d3, Source = "fromid", Target = "toid", 
                     NodeID = "NAME", Group = "id", Value = "weight10", 
                     opacity = 1, fontSize = 16, zoom = FALSE, Nodesize = "logn",
                     linkDistance = 100, height = 1000, arrows = TRUE)
    })

```

# ERGM

```{r}

# #### Data Cleaning
# df = fed %>%
#   filter(yr == 1990) %>%
#   filter(n >= 5000) %>%
#   filter(n_nextpct <= .5) 
# 
# 
# #### Make nodes
# sources = df %>%
#   distinct(AGYSUB) %>%
#   rename(label = AGYSUB)
# 
# destinations = df %>%
#   distinct(label = AGYSUB_next)
# 
# nodes = full_join(sources, destinations, by = "label")
# 
# nodes = nodes %>%
#   rowid_to_column("id")
# 
# #### Add covariates to nodes
# 
# ref2 = ref %>%
#   filter(yr == 1990) %>%
#   select(AGYSUB, n, agy_typ, med_sal_)
# 
# nodes = nodes %>%
#   left_join(ref2, by = c("label" = "AGYSUB")) %>%
#   drop_na()
# 
# #### Make edges
# 
# agy_set = expand.grid(unique(df$AGYSUB), unique(df$AGYSUB_next))
# 
# agy_set = agy_set %>%
#   filter(as.character(Var1) != as.character(Var2)) %>%
#   rename(AGYSUB = Var1, AGYSUB_next = Var2)
# 
# df2 = agy_set %>%
#   left_join(df) %>%
#   mutate(connected = ifelse(n_next > 0, 1, 0)) 
# 
# df2$connected = replace_na(df2$connected, 0)
# 
# df2 = df2 %>%
#   select(AGYSUB, AGYSUB_next, connected)
# 
# df2 = df2 %>%
#   left_join(nodes, by = c("AGYSUB" = "label")) %>%
#   rename(from = id)
# 
# df2 = df2 %>%
#   left_join(nodes, by = c("AGYSUB_next" = "label")) %>%
#   rename(to = id)
# 
# df2 = df2 %>%
#   filter(from != to) %>%
#   filter(connected == 1)
# 
# #### Make network
# 
# fednetwork = network(df2, vertex.attr = nodes, matrix.type = "edgelist")

```

## Simple ERGM Code

```{r, echo = TRUE}

# set.seed(442210)
# 
# model1 = ergm(fednetwork ~ edges + nodecov("med_sal_") + 
#                 nodematch("agy_typ") +
#                 nodecov("n") +
#                 mutual + gwidegree(2), 
#              control=control.ergm(
#                MCMC.samplesize=20000,
#                MCMC.burnin=500000,
#                MCMLE.maxit=10,
#                parallel = 4))

```

## Results

```{r}

# gof1 = gof(model1)
# 
# par(mfrow=c(3,2))
# plot(gof1)


```

## MCMC Diagnostics

```{r, results='hide'}

# mcmc.diagnostics(model1)

```

## TERGM

```{r}


years = seq(1974, 2012, by = 1)

nets = list()

df = fed %>%
  filter(n >= 5000) %>%
  filter(n <= 20000) %>%
  filter(n_nextpct <= .5)

sources = df %>%
  distinct(NAME) %>%
  rename(label = NAME)

destinations = df %>%
  distinct(label = NAME_next)

nodes = full_join(sources, destinations, by = "label")

nodes = nodes %>%
  rowid_to_column("id")

#######################################################

for (i in 1:length(years)) {
  
  df = fed %>%
    filter(yr == years[i]) %>%
    filter(n >= 1000) %>%
    filter(n <= 20000) %>%
    filter(n_nextpct <= .5)
  
  #### Add covariates to nodes
  
  ref2 = ref %>%
    filter(yr == years[i]) %>%
    select(n, agy_typ, med_sal_, agy_full) %>%
    mutate(agy_full = toupper(agy_full))
  
  nodestemp = nodes %>%
    left_join(ref2, by = c("label" = "agy_full")) %>%
    drop_na()
  
  #### Make edges
  
  agy_set = expand.grid(unique(df$NAME), unique(df$NAME_next))
  
  agy_set = agy_set %>%
    filter(as.character(Var1) != as.character(Var2)) %>%
    rename(NAME = Var1, NAME_next = Var2)
  
  df2 = agy_set %>%
    left_join(df) %>%
    mutate(connected = ifelse(n_next > 10, 1, 0)) 
  
  df2$connected = replace_na(df2$connected, 0)
  
  df2 = df2 %>%
    select(NAME, NAME_next, connected)
  
  df2 = df2 %>%
    left_join(nodestemp, by = c("NAME" = "label")) %>%
    rename(from = id)
  
  df2 = df2 %>%
    left_join(nodestemp, by = c("NAME_next" = "label")) %>%
    rename(to = id)
  
  df2 = df2 %>%
    filter(from != to) %>%
    filter(connected == 1)
  
  #### Make network
  
  temp = network(df2, vertex.attr = nodestemp, matrix.type = "edgelist")
  nets[[i]] = temp
  
  
}

sampdyn = networkDynamic(network.list = nets, vertex.pid = "vertex.names")



```

## Tergm2

```{r, results='asis'}

render.d3movie(sampdyn, 
               plot.par=list(displaylabels=T, label.cex = .45), 
               label = network.vertex.names(sampdyn), 
               render.par=list(tween.frames=10,
                               show.time=TRUE,
                               show.stats= "~edges+triangles",
                               extraPlotCmds=NULL,
                               initial.coords=0),
               d3.options = list(animateOnLoad = FALSE, animationDuration = 3000,
                                 durationControl=TRUE),
               output.mode = 'inline')

```

# In the evening

## Dinner

- Eat spaghetti
- Drink wine

---